Repository projeto-spider/labes-2019, pull requests merged in 2019-07, with the labels that each got.

#210 Adiciona HTTP services
  components/StudentComboBox.vue
  front/defenses/service.js
  front/documents/service.js
  front/pendencies/service.js
  front/selector.js
  front/service.js
  front/solicitations/service.js
  front/students/service.js
  front/subjects/service.js
  front/users/service.js
  nuxt.config.js
  plugins/service.js
  test/front/selector.spec.js
Labels: enhancement

#229 Configurações e deploy
  .env.example
  README.md
  ecosystem.config.js
  knexfile.js
  package-lock.json
  package.json
  seeds/1-users.js
  seeds/2-students.js
  seeds/3-subjects.js
  seeds/4-solicitations.js
  seeds/5-pendencies.js
  seeds/6-documents.js
  server/config.js
  server/controllers/documents/Upload.js
  server/index.js
  server/router.js
  server/utils.js
  test/server/controllers/documents.spec.js
  test/use-seeds-data/documents.js
  test/use-seeds.js
Labels: enhancement

#207 Refatoração e bug-fix para o Frontend
  components/AdmissionForm.vue
  components/EmailListCompare.vue
  components/EmailListComponent.vue
  components/ImportStudents.vue
  components/ModalPrescribedList.vue
  components/SearchInput.vue
  components/StudentComboBox.vue
  components/TccDefenseSearch.vue
  front/defenses/service.js
  front/documents/service.js
  front/pendencies/service.js
  front/service.js
  front/solicitations/service.js
  front/students/service.js
  front/subjects/service.js
  front/users/service.js
  layouts/default.vue
  nuxt.config.js
  pages/activeStudents.vue
  pages/allStudents.vue
  pages/concludingAdmission.vue
  pages/concludingStudents.vue
  pages/emailListActive.vue
  pages/emailListFreshman.vue
  pages/emailListNewsletter.vue
  pages/formingStudents.vue
  pages/freshmenAdmission.vue
  pages/index.vue
  pages/login.vue
  pages/signup.vue
  pages/subjects.vue
  pages/tccDefense.vue
  pages/teacher/registerPresentation.vue
  plugins/service.js
  store/auth.js
Labels: bug-fix, enhancement, refactor

#230 Adiciona rota para Atualização de Usuários
  server/controllers/users/Update.js
  server/controllers/users/index.js
  server/router.js
  test/server/controllers/users.spec.js
Labels: enhancement

#160 M13 Daniel Teoian back
  migrations/20190506212942_students.js
  server/controllers/students/List.js
  test/server/controllers/students.spec.js
  test/use-seeds-data/students.js
Labels: enhancement

#232 Graduandos não podem ter pendências
  components/StudentComboBox.vue
  server/controllers/students/FromCsv.js
  server/utils.js
  test/server/utils.spec.js
Labels: Arquitetura

#237 Formulário de login aceita enter mesmo estando no checkbox
  pages/login.vue
Labels: bug, bug-fix

#222 Validação de parâmetros nas requisições e atualização da WIKI
  server/controllers/auth/Login.js
  server/controllers/auth/Show.js
  server/controllers/defenses/Create.js
  server/controllers/defenses/List.js
  server/controllers/defenses/Update.js
  server/controllers/documents/Delete.js
  server/controllers/documents/List.js
  server/controllers/documents/Show.js
  server/controllers/documents/Upload.js
  server/controllers/documents/View.js
  server/controllers/pendencies/FromBatch.js
  server/controllers/pendencies/List.js
  server/controllers/pendencies/Show.js
  server/controllers/solicitations/Create.js
  server/controllers/students/ActiveMailList.js
  server/controllers/students/EmailChanges.js
  server/controllers/students/FromCsv.js
  server/controllers/students/List.js
  server/controllers/students/Show.js
  server/controllers/students/Update.js
  server/controllers/students/UpdateAcademicHighlight.js
  server/controllers/students/UpdateMailingList.js
  server/controllers/subjects/Create.js
  server/controllers/subjects/Delete.js
  server/controllers/subjects/List.js
  server/controllers/subjects/Show.js
  server/controllers/subjects/Update.js
  server/controllers/users/Create.js
  server/controllers/users/List.js
  server/controllers/users/Show.js
  server/controllers/users/Update.js
  server/router.js
  server/utils.js
  shared/errors.js
  test/server/controllers/auth.spec.js
  test/server/controllers/defenses.spec.js
  test/server/controllers/documents.spec.js
  test/server/controllers/pendencies.spec.js
  test/server/controllers/solicitations.spec.js
  test/server/controllers/students.spec.js
  test/server/controllers/subjects.spec.js
  test/server/controllers/users.spec.js
Labels: enhancement

#240 Confirma que mudanças de apto~não apto acontecem.
  server/controllers/documents/Delete.js
  server/models/Student.js
  server/utils.js
  test/server/controllers/students.spec.js
  test/use-seeds-data/students.js
Labels: enhancement

#247 Front agora envia CD, recarregar as listas quando move e refatoração dos parametros do search input
  components/SearchInput.vue
  components/StudentComboBox.vue
  front/students/service.js
  pages/formingStudents.vue
Labels: bug, bug-fix, refactor

#245 Fix navbars
  components/AsideBar.vue
  layouts/default.vue
Labels: bug-fix

#239 Remove campos não usados nos estudantes
  migrations/20190506212942_students.js
  server/controllers/students/Update.js
  server/models/Student.js
  test/server/controllers/students.spec.js
  test/server/models/student.spec.js
  test/use-seeds-data/students.js
Labels: bug

#215 Página de acompanhamento de defesas do professor
  components/DatePicker.vue
  components/DefenseForm.vue
  components/TccDefenseSearch.vue
  layouts/defaultTeacher.vue
  pages/tccDefense.vue
  pages/teacher/home.vue
Labels: enhancement

#161 Create PDF Daniel Jairo
  migrations/20190623214136_defenses.js
  package-lock.json
  package.json
  server/controllers/defenses/TccGenerate.js
  server/controllers/defenses/index.js
  server/models/tccdocs/ata.js
  server/models/tccdocs/cd.js
  server/models/tccdocs/certificado.js
  server/models/tccdocs/credenciamento.js
  server/models/tccdocs/divulgacao.js
  server/models/tccdocs/img/checkbox.png
  server/models/tccdocs/img/logoFacomp.png
  server/models/tccdocs/img/logoUFPA.png
  server/router.js
  test/server/controllers/defenses.spec.js
Labels: Meta

#249 Corrige filtros no serviço de defesas
  front/defenses/service.js
Labels: bug

#236 Fix Página de cadastro de usuários
  components/AsideBar.vue
  components/InputValidation.vue
  pages/signup.vue
Labels: bug, bug-fix

#258 Adiciona página de erro
  layouts/error.vue
Labels: bug, bug-fix

#244 Muda funções síncronas para assíncronas
  package-lock.json
  package.json
  server/controllers/documents/Delete.js
  server/controllers/documents/Upload.js
  server/controllers/documents/View.js
  test/server/controllers/documents.spec.js
Labels: bug

#221 Meta 25: Gerar modelo de divulgação de Defesa de TCC
  components/TccDefenseSearch.vue
  pages/tccDefense.vue
Labels: Meta

#257 Ajustes front
  components/EmailListCompare.vue
  components/ModalPrescribedList.vue
  components/SearchInput.vue
  components/StudentComboBox.vue
  front/students/service.js
Labels: bug, bug-fix, enhancement, refactor

#261 Usa 10 segundos para teste lento
  server/utils.js
  test/server/controllers/auth.spec.js
  test/server/controllers/defenses.spec.js
  test/server/controllers/documents.spec.js
  test/server/controllers/pendencies.spec.js
  test/server/controllers/solicitations.spec.js
  test/server/controllers/students.spec.js
  test/server/controllers/subjects.spec.js
  test/server/controllers/users.spec.js
Labels: bug

#268 Conserta AsideBar
  components/AsideBar.vue
Labels: bug

#269 Remove --inspect do npm run dev
  package.json
Labels: bug

#292 Trocar "Matérias" por "Componentes Curriculares" na sidebar
  components/AsideBar.vue
Labels: enhancement

#295 Mover botão da Lista de Prescrição para a sidebar
  components/AsideBar.vue
  components/ModalPrescribedList.vue
  pages/formingStudents.vue
Labels: enhancement

#299 Corrige isAcademicHighlight para academicHighlight
  front/students/service.js
  pages/concludingStudents.vue
Labels: bug

#300 Ajeita serviço de importação de CSV
  front/students/service.js
Labels: bug

#264 Adiciona e testa defenseId nos estudantes
  components/DefenseForm.vue
  components/StudentComboBox.vue
  front/defenses/service.js
  migrations/20190506212942_students.js
  server/controllers/defenses/Create.js
  server/controllers/defenses/Show.js
  server/controllers/defenses/Update.js
  server/controllers/defenses/index.js
  server/controllers/defenses/registrationNumbersToStudents.js
  server/controllers/students/Update.js
  server/router.js
  shared/errors.js
  test/server/controllers/defenses.spec.js
  test/server/controllers/students.spec.js
  test/server/router.spec.js
  test/use-seeds-data/students.js
Labels: enhancement

#298 Desabilitar botão de Eleger Destaque Acadêmico
  pages/formingStudents.vue
Labels: Frontend, enhancement

#296 fix defensas não mudam de status
  front/defenses/service.js
Labels: bug, bug-fix

#259 Visualização de PDFs
  components/DefenseForm.vue
  components/TccDefenseSearch.vue
  front/defenses/service.js
  pages/teacher/registerPresentation.vue
  server/controllers/defenses/TccGenerate.js
  server/models/tccdocs/certificado.js
  server/models/tccdocs/credenciamento.js
  test/server/controllers/defenses.spec.js
Labels: Meta

#297 Permite atualização do nome do usuário e
  server/controllers/users/Update.js
  test/server/controllers/users.spec.js
Labels: Backend

#265 Tornar data do modelo de divulgação por extenso
  components/AsideBar.vue
  components/TccDefenseSearch.vue
Labels: refactor

#303 Defesa com status "done" teve ter nota
  server/controllers/defenses/Update.js
  shared/errors.js
  test/server/controllers/defenses.spec.js
Labels: Backend, enhancement

#304 Garante que não tem como fugir de missingCollation
  server/utils.js
  test/server/controllers/students.spec.js
  test/server/utils.spec.js
Labels: Backend, enhancement

#291 Tirar o "cancelar" do combo box de defesa.
  components/DefenseForm.vue
Labels: bug-fix

#308 Add favicon
  static/favicon.ico
  static/icon.png
Labels: enhancement

#306 Atualização nas rotas de listas de emails
  server/controllers/students/EmailChanges.js
  server/controllers/students/UpdateMailingList.js
  test/server/controllers/students.spec.js
Labels: Backend, enhancement

#302 Adiciona campo fullName nos usuários
  components/StudentComboBox.vue
  layouts/default.vue
  layouts/defaultTeacher.vue
  migrations/20190426155412_users.js
  server/controllers/users/Create.js
  server/controllers/users/Update.js
  test/server/controllers/users.spec.js
  test/server/models/user.spec.js
  test/use-seeds-data/users.js
Labels: Backend, Frontend, enhancement

#309 Permite filtro de usuários por username
  server/controllers/users/List.js
  test/server/controllers/users.spec.js
Labels: Backend, enhancement

#310 Professores não podem ver documentos no combo box da defesa
  components/DefenseForm.vue
  components/TccDefenseSearch.vue
Labels: bug-fix

#311 Mover botão "Eleger Destaque Acadêmico"
  components/SearchInput.vue
  pages/formingStudents.vue
Labels: Frontend

#312 `term` só em formandos, graduandos e concluintes
  server/controllers/students/Update.js
  test/server/controllers/students.spec.js
Labels: Backend, enhancement

#266 Fix página de mudanças de mailing list
  components/EmailListCompare.vue
  components/EmailListComponent.vue
  front/students/service.js
Labels: enhancement, invalid

#305 Adiciona campo de falta à colação de grau
  components/SearchInput.vue
  components/StudentComboBox.vue
  front/students/service.js
Labels: Frontend, enhancement

#320 Imagem na pagina de login
  pages/login.vue
Labels: bug, bug-fix

#324 Listar usuários ignorando a paginação
  server/controllers/users/List.js
  test/server/controllers/users.spec.js
Labels: Backend, enhancement

#301 Refatoração do formulário de TCC
  components/DefenseForm.vue
Labels: Frontend, bug-fix

#290 Adição do input de curso e forma de ingresso para o front-end e back-end
  components/AdmissionForm.vue
  front/solicitations/service.js
  layouts/admissionLayout.vue
  migrations/20190524215233_solicitations.js
  server/controllers/solicitations/Create.js
  test/server/controllers/solicitations.spec.js
  test/use-seeds-data/solicitations.js
Labels: Frontend, enhancement

#314 Adiciona `*IsTeacher` para a banca
  migrations/20190623214136_defenses.js
  server/controllers/defenses/Create.js
  server/controllers/defenses/Update.js
  server/models/Defense.js
  test/server/controllers/defenses.spec.js
  test/server/models/defense.spec.js
Labels: Backend, enhancement

#313 Adiciona rota de deletar defesa
  server/controllers/defenses/Delete.js
  server/controllers/defenses/index.js
  server/router.js
  test/server/controllers/defenses.spec.js
Labels: Backend, enhancement

#321 Front end Excluir Defesa
  components/DefenseForm.vue
  components/TccDefenseSearch.vue
  front/defenses/service.js
  front/students/service.js
  server/controllers/students/List.js
  test/server/controllers/students.spec.js
Labels: Frontend, enhancement

#327 Fix defesas TCC e atualiza CSS do formulário de admissão
  components/TccDefenseSearch.vue
  layouts/admissionLayout.vue
  pages/teacher/home.vue
Labels: Frontend, bug, bug-fix

#325 Ajustes em combobox e DocumentRow
  components/StudentComboBox.vue
  components/StudentComboBox/DocumentRow.vue
Labels: Frontend, bug, bug-fix

#330 Cria a API de Settings
  migrations/20190706153229_settings.js
  server/Setting.js
  server/controllers/settings/List.js
  server/controllers/settings/Show.js
  server/controllers/settings/Update.js
  server/controllers/settings/index.js
  server/models/Setting.js
  server/router.js
  test/server/controllers/settings.spec.js
  test/server/models/setting.spec.js
Labels: Backend, enhancement

#331 Adiciona fullName para atualizar e criar usuário.
  components/UserForm.vue
  front/users/service.js
  store/auth.js
Labels: Frontend, enhancement

#328 Criação de um checkbox para saber se é professor ou não.
  components/DefenseForm.vue
  components/TccDefenseSearch.vue
  front/defenses/service.js
  pages/teacher/home.vue
Labels: Frontend, enhancement

#338 Atualizar o usuário não limpa o formulário
  components/UserForm.vue
Labels: Frontend, bug, bug-fix

#339 Melhoras no modal e formulário de defesa
  components/DefenseForm.vue
  components/StudentComboBox.vue
  components/TccDefenseSearch.vue
  front/defenses/service.js
  pages/teacher/registerPresentation.vue
Labels: Frontend, enhancement

#341 Tratar notificações desnecessárias no modal de Gerar destaque acadêmico.
  pages/formingStudents.vue
Labels: Frontend

#342 fix layout de professor
  pages/teacher/updateUser.vue
Labels: Frontend, bug-fix

#344 Não modificar a defesa até salvar
  components/DatePicker.vue
  components/DefenseForm.vue
  components/TccDefenseSearch.vue
  components/TimePicker.vue
Labels: Frontend, bug

#343 Fix tests front
  test/front/login.spec.js
Labels: bug, bug-fix

#347 Atualizações no modelo de PDF da Lista de Frequência.
  server/models/tccdocs/listaFrequencia.js
Labels: enhancement

#360 Alterar cor do destaque academico, porem faltou colação
  components/SearchInput.vue
Labels: Frontend

#368 Professor pode atualizar defesas pendentes
  server/controllers/defenses/Update.js
  server/router.js
  test/server/controllers/defenses.spec.js
Labels: Backend, enhancement

#365 Formata hora de acordo com modelo de divulgação
  components/TccDefenseSearch.vue
Labels: refactor

#364 Refatora componente de validação para usar InputValidation
  components/AdmissionForm.vue
Labels: Frontend, bug-fix

#362 Reparos nos modelos de PDF
  server/models/tccdocs/certificadoConclusao.js
  server/models/tccdocs/listaFrequencia.js
Labels: bug
