Repository projeto-spider/labes-2019, pull requests merged in 2019-05, with the labels that each got.

#6 Adiciona modelo de Student e algumas rotas
  migrations/20190506212942_students.js
  server/controllers/students/List.js
  server/controllers/students/Show.js
  server/controllers/students/index.js
  server/models/Student.js
  server/router.js
  test/server/models/student.spec.js
Labels: enhancement

#9 Meta 6 US4: Importar CSV para a tabela students
  migrations/20190506212942_students.js
  server/utils.js
  test/server/utils.spec.js
Labels: enhancement

#15 Padronização de configuração
  .vscode/settings.json
  package.json
Labels: enhancement

#12 Meta 6 US3: Endpoint de upload
  .editorconfig
  package-lock.json
  package.json
  server/controllers/students/FromCsv.js
  server/controllers/students/index.js
  server/index.js
  server/router.js
  shared/errors.js
  test/server/controllers/students.spec.js
  test/server/controllers/users.spec.js
  test/server/fixtures/sigaa/valid.csv
  test/server/fixtures/sigaa/wrong-col-number.csv
  test/server/fixtures/sigaa/wrong-headers.csv
  test/server/fixtures/sigaa/wrong-invalid-csv.csv
  test/server/fixtures/sigaa/wrong-length.csv
Labels: enhancement

#16 Usa commonjs no arquivo server/utils.js
  server/utils.js
Labels: enhancement

#17 Semente dos estudantes criada
  seeds/students.js
Labels: enhancement

#13 M06 US02 a 05 Adicionar alunos totais a ferramenta Front-end.
  components/importStudents.vue
  components/searchInput.vue
  layouts/default.vue
  layouts/empty.vue
  middleware/auth.js
  pages/allStudents.vue
  pages/login.vue
Labels: enhancement

#35 Não usa seeds no teste de utils
  test/server/utils.spec.js
Labels: bug

#36 Configura Travis CI
  .travis.yml
  package.json
Labels: enhancement

#37 Combo box
  components/importStudents.vue
  components/searchInput.vue
  components/studentComboBox.vue
  layouts/default.vue
  middleware/course.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/activeStudents.vue
  pages/allStudents.vue
  pages/emailList.vue
  pages/importar/importarAlunos.vue
Labels: enhancement

#43 Corrigido erro de importar error de um arquivo com CommonJS
  components/importStudents.vue
  nuxt.config.js
Labels: enhancement

#45 Adiciona cabeçalhos de paginação na API
  server/controllers/students/List.js
  server/controllers/users/List.js
  server/utils.js
  test/server/controllers/students.spec.js
  test/server/controllers/users.spec.js
Labels: enhancement

#49 Meta 14 (André & Lakshamana)
  components/importStudents.vue
  components/searchInput.vue
  components/studentComboBox.vue
  pages/activeStudents.vue
  pages/allStudents.vue
  server/controllers/students/FromCsv.js
  server/controllers/students/List.js
  server/utils.js
  shared/errors.js
  test/server/controllers/students.spec.js
  test/server/fixtures/sigaa/last-line-blank.csv
Labels: Meta

#52 Aceita CSV grandes na importação de estudantes
  server/utils.js
  test/server/fixtures/sigaa/big.csv
  test/server/utils.spec.js
Labels: bug

#48 Meta 07: Gerenciar arquivos, pendências e requisitos do aluno & Meta 05: Buscar informações sobre um aluno
  .gitignore
  components/importStudents.vue
  components/mixins/errors.js
  components/searchInput.vue
  components/studentComboBox.vue
  layouts/default.vue
  migrations/20190514100227_documents.js
  nuxt.config.js
  package.json
  pages/allStudents.vue
  seeds/documents.js
  seeds/students.js
  server/controllers/documents/List.js
  server/controllers/documents/Show.js
  server/controllers/documents/Upload.js
  server/controllers/documents/View.js
  server/controllers/documents/index.js
  server/controllers/students/Update.js
  server/controllers/students/index.js
  server/models/Document.js
  server/router.js
  shared/enums.js
  shared/errors.js
  test/server/controllers/documents.spec.js
  test/server/controllers/students.spec.js
  test/server/fixtures/pdf/file_invalid.txt
  test/server/fixtures/pdf/test.pdf
  test/server/models/documents.spec.js
  test/server/router.spec.js
Labels: Meta

#47 Meta 15: autenticação do usuário
  migrations/20190426155412_users.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/login.vue
  pages/signup.vue
  plugins/axios.js
  seeds/users.js
  server/controllers/auth/Login.js
  server/controllers/auth/Show.js
  server/controllers/auth/index.js
  server/controllers/users/Create.js
  server/controllers/users/index.js
  server/db.js
  server/error-handler.js
  server/index.js
  server/models/User.js
  server/router.js
  server/utils.js
  shared/errors.js
  store/auth.js
  test/server/controllers/auth.spec.js
  test/server/controllers/documents.spec.js
  test/server/controllers/students.spec.js
  test/server/controllers/users.spec.js
  test/server/models/user.spec.js
  test/server/router.spec.js
  test/server/test-utils.js
Labels: enhancement

#54 Reutiliza middleware de body parsing no router.js
  server/router.js
Labels: enhancement

#55 Hotfix para ordenação e paginação
  components/searchInput.vue
  components/studentComboBox.vue
  pages/allStudents.vue
  server/router.js
  test/server/controllers/auth.spec.js
Labels: bug

#84 Correções estéticas
  components/importStudents.vue
  components/mixins/studentStatus.js
  components/searchInput.vue
  components/studentComboBox.vue
  layouts/default.vue
  package-lock.json
Labels: bug

#98 Meta 08 Ordenação por CRG
  seeds/students.js
  server/controllers/students/List.js
  test/server/controllers/students.spec.js
Labels: enhancement

#95 Remove knex raw
  server/utils.js
Labels: enhancement

#99 Adição de campo de email editável ao combo box.
  components/studentComboBox.vue
Labels: Meta

#96 Trata CRG
  components/studentComboBox.vue
  server/models/Student.js
  test/server/models/student.spec.js
Labels: bug

#103 bug da issue #64, que evita o erro quando o usuário desiste de fazer upload de arquivo no comboBox pela segunda vez.
  components/studentComboBox.vue
Labels: bug

#100 M01 Endpoint String de Emails
  seeds/students.js
  server/controllers/students/ActiveMailList.js
  server/controllers/students/List.js
  server/controllers/students/index.js
  server/router.js
  test/server/controllers/students.spec.js
  test/server/models/user.spec.js
Labels: Meta

#104 Atualiza tabela de estudantes
  migrations/20190506212942_students.js
  seeds/students.js
  test/server/controllers/students.spec.js
Labels: enhancement

#97 M-03 Endpoint de requisições de entrada na lista de email
  migrations/20190524215233_solicitations.js
  seeds/solicitations.js
  server/controllers/solicitations/Create.js
  server/controllers/solicitations/index.js
  server/models/Solicitation.js
  server/router.js
  test/server/controllers/solicitations.spec.js
Labels: enhancement

#110 Verifica se há um objeto em StudentCsv para poder utilizá-lo.
  components/importStudents.vue
Labels: bug

#101 Crud Materias Back End Daniel
  migrations/20190527115705_subjects.js
  seeds/subjects.js
  server/controllers/subjects/Create.js
  server/controllers/subjects/Delete.js
  server/controllers/subjects/List.js
  server/controllers/subjects/Show.js
  server/controllers/subjects/Update.js
  server/controllers/subjects/index.js
  server/models/Subject.js
  server/router.js
  test/server/controllers/subjects.spec.js
  test/server/models/subjects.spec.js
Labels: Meta

#113 fix do fix do Truncamento de CRG
  components/studentComboBox.vue
Labels: bug

#102 Metas 02 e 03 lakshamana (frontend)
  components/admission.vue
  components/searchInput.vue
  layouts/admissionLayout.vue
  layouts/default.vue
  pages/concludingAdmission.vue
  pages/concludingStudents.vue
  pages/freshmenAdmission.vue
Labels: Meta

#119 Meta 08 - Página de formandos
  components/searchInput.vue
  layouts/default.vue
  pages/formingStudents.vue
Labels: Meta

#114 Remove atributo note da tabela de estudantes
  migrations/20190506212942_students.js
  seeds/students.js
  test/server/controllers/students.spec.js
Labels: Arquitetura

#127 Corrige atualização de dados do estudante [Back]
  server/controllers/students/Update.js
  test/server/controllers/students.spec.js
Labels: bug

#124 Remove overwrite da classe container em admissionLayout
  layouts/admissionLayout.vue
Labels: bug

#128 Adicionar informações adicionais no modal dos usuários
  components/studentComboBox.vue
Labels: enhancement

#120 Corrige o filtro de e-mail
  server/controllers/students/List.js
  test/server/controllers/students.spec.js
Labels: bug

#115 CRUD de matérias necessário para futuras modificações
  components/exportEmailList.vue
  layouts/default.vue
  migrations/20190527115705_subjects.js
  pages/emailList.vue
  pages/subjects.vue
  seeds/subjects.js
  server/controllers/subjects/Create.js
  server/controllers/subjects/Update.js
  test/server/controllers/subjects.spec.js
  test/server/models/subjects.spec.js
Labels: enhancement

#122 Corrige a importação de alunos via CSV
  components/mixins/errors.js
  server/controllers/students/FromCsv.js
  server/utils.js
  shared/errors.js
  test/server/controllers/students.spec.js
  test/server/fixtures/sigaa/wrong-registration-number.csv
Labels: bug

#126 Meta 8: Gerar de forma prática o destaque acadêmico.
  components/searchInput.vue
  layouts/default.vue
  pages/formingStudents.vue
  server/controllers/students/List.js
  server/controllers/students/UpdateAcademicHighlight.js
  server/controllers/students/index.js
  server/router.js
  test/server/controllers/students.spec.js
Labels: Meta

#112 m01us04 - Criado o botão que gera string de emails
  components/exportEmailList.vue
  pages/emailList.vue
Labels: Meta
