Repository projeto-spider/labes-2019, pull requests merged in 2019-06, with the labels that each got.

#138 Adicionado validação de tamanho de arquivo ao upload
  components/importStudents.vue
  components/mixins/errors.js
  components/studentComboBox.vue
  nuxt.config.js
  shared/config.js
  shared/errors.js
Labels: enhancement

#139 Create LICENSE
  LICENSE
Labels: enhancement

#140 Corrige bug em que o cd não era salvo no banco de dados
  components/studentComboBox.vue
Labels: bug

#141 Meta 10 - Gerar lista de prescrição #132
  seeds/students.js
  server/controllers/students/List.js
  test/server/controllers/students.spec.js
Labels: Meta

#143 Meta 04: Gerenciar status dos alunos graduandos #130
  server/controllers/documents/Upload.js
  server/controllers/students/Update.js
  server/utils.js
  test/server/utils.spec.js
Labels: Meta

#146 Meta 11: Geração da lista de destaques acadêmicos - lakshamana e souzaluuk
  components/mixins/errors.js
  components/searchInput.vue
  pages/concludingStudents.vue
  test/server/controllers/students.spec.js
Labels: Meta

#147 CRUD de Pendências
  components/studentComboBox.vue
  migrations/20190605024900_pendencies.js
  seeds/pendencies.js
  server/controllers/pendencies/FromBatch.js
  server/controllers/pendencies/List.js
  server/controllers/pendencies/Show.js
  server/controllers/pendencies/index.js
  server/controllers/subjects/List.js
  server/models/Pendency.js
  server/router.js
  test/server/controllers/pendencies.spec.js
  test/server/controllers/subjects.spec.js
  test/server/models/pendencies.spec.js
Labels: enhancement

#145 Meta 10: Gerar lista de alunos presentes na lista de prescrição #132
  components/modalPrescribedList.vue
  components/studentComboBox.vue
  pages/formingStudents.vue
Labels: Meta

#148 Meta 20: Gerar lista de alterações que devem ser realizadas no Google Groups
  components/emailListCompare.vue
  components/emailListComponent.vue
  components/searchInput.vue
  layouts/default.vue
  migrations/20190506212942_students.js
  package-lock.json
  package.json
  pages/allStudents.vue
  pages/emailList.vue
  pages/emailListActive.vue
  pages/emailListFreshman.vue
  pages/emailListNewsletter.vue
  pages/formingStudents.vue
  seeds/students.js
  server/controllers/students/EmailChanges.js
  server/controllers/students/UpdateMailingList.js
  server/controllers/students/index.js
  server/router.js
  server/utils.js
  test/server/controllers/students.spec.js
  test/server/utils.spec.js
Labels: Meta

#162 Meta 21 (Utilizado pelo Professor): Gerar dados do TCC utilizando formulário.
  components/datepicker.vue
  components/timepicker.vue
  layouts/defaultTeacher.vue
  middleware/auth.js
  middleware/course.js
  migrations/20190623214136_defenses.js
  pages/login.vue
  pages/teacher/home.vue
  pages/teacher/registerPresentation.vue
  server/controllers/defenses/Create.js
  server/controllers/defenses/index.js
  server/models/Defense.js
  server/router.js
  test/server/controllers/defenses.spec.js
  test/server/models/defense.spec.js
Labels: Meta

#163 M22 lakshamana front
  components/datepicker.vue
  components/defenseForm.vue
  components/studentComboBox.vue
  components/tccDefenseSearch.vue
  components/timepicker.vue
  layouts/default.vue
  migrations/20190623214136_defenses.js
  pages/tccDefense.vue
  pages/teacher/registerPresentation.vue
  server/controllers/defenses/Create.js
  server/controllers/defenses/List.js
  server/controllers/defenses/Update.js
  server/controllers/defenses/index.js
  server/router.js
  test/server/controllers/defenses.spec.js
Labels: Meta

#164 Hotfix para lista de email
  components/emailListCompare.vue
  components/searchInput.vue
Labels: bug

#157 Fix bugs casos de teste v0.3.0
  components/searchInput.vue
  components/studentComboBox.vue
  server/controllers/documents/Delete.js
  server/controllers/documents/Upload.js
  server/controllers/documents/index.js
  server/router.js
  server/utils.js
  test/server/controllers/documents.spec.js
Labels: bug

#200 Pequenas melhoras no Combo Box
  components/datepicker.vue
  components/studentComboBox.vue
  components/studentComboBox/BaseStudentDataRow.vue
  components/studentComboBox/documentRow.vue
  front/persistence.js
  layouts/default.vue
  store/auth.js
  store/index.js
Labels: bug, enhancement

#202 Cria comando makedb
  README.md
  package.json
Labels: enhancement

#214 Alterações no backend
  knexfile.js
  package.json
  seeds/documents.js
  seeds/pendencies.js
  seeds/solicitations.js
  seeds/students.js
  seeds/subjects.js
  seeds/users.js
  server/controllers/students/List.js
  server/models/Student.js
  test/seeds.js
  test/server/controllers/auth.spec.js
  test/server/controllers/defenses.spec.js
  test/server/controllers/documents.spec.js
  test/server/controllers/pendencies.spec.js
  test/server/controllers/solicitations.spec.js
  test/server/controllers/students.spec.js
  test/server/controllers/subjects.spec.js
  test/server/controllers/users.spec.js
  test/server/models/defense.spec.js
  test/server/models/documents.spec.js
  test/server/models/pendencies.spec.js
  test/server/models/student.spec.js
  test/server/models/subjects.spec.js
  test/server/models/user.spec.js
  test/server/router.spec.js
  test/server/test-utils.js
  test/use-seeds-data/documents.js
  test/use-seeds-data/pendencies.js
  test/use-seeds-data/solicitations.js
  test/use-seeds-data/students.js
  test/use-seeds-data/subjects.js
  test/use-seeds-data/users.js
  test/use-seeds.js
Labels: enhancement

#213 Garantir que o professor tenha acesso a defesas que são apenas as suas
  server/controllers/defenses/List.js
  server/router.js
  test/server/controllers/defenses.spec.js
Labels: enhancement
